name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install mise
        uses: jdx/mise-action@v2
      - name: Display Go version
        run: go version

      - name: Download Dependencies
        run: go mod download

      - name: Test
        run: mise run cover

      - name: Upload coverage
        uses: codecov/codecov-action@v4.6.0
        with:
          files: ./cover.out
          token: ${{ secrets.CODECOV_TOKEN }}