name: Publish release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release (e.g. v1.0.0)
        required: true
        type: string
      ref:
        description: Git ref to release from (usually main)
        required: true
        default: main
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Validate version format
        run: |
          if [[ ! "${{ inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version must be in format v1.2.3"
            exit 1
          fi

      - name: Run tests
        run: make test

      - name: Extract changelog
        run: |
          if [ -f ".changes/${{ inputs.version }}.md" ]; then
            tail -n+3 .changes/${{ inputs.version }}.md > /tmp/release-notes.txt
          else
            echo "Release ${{ inputs.version }}" > /tmp/release-notes.txt
            echo "" >> /tmp/release-notes.txt
            echo "## Changes" >> /tmp/release-notes.txt
            echo "- Bug fixes and improvements" >> /tmp/release-notes.txt
          fi

      - name: Create and push tag
        run: |
          git tag "${{ inputs.version }}"
          git push origin "${{ inputs.version }}"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --release-notes /tmp/release-notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}